samples:
  SRR2073144 : SRR2073144
  SRR2073145 : SRR2073145

tophat: tophat-2.1.1.Linux_x86_64/tophat
annotation: references/Arabidopsis_thaliana/Ensembl/TAIR10/Annotation/Genes/genes.gtf
bowtie_index: references/Arabidopsis_thaliana/Ensembl/TAIR10/Sequence/Bowtie2Index/genome
genome: references/Arabidopsis_thaliana/Ensembl/TAIR10/Sequence/WholeGenomeFasta/genome.fa
assembly: assembly-1-2.txt
merged: merged_asm/merged.gtf